default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DEVELOPMENT_DATABASE_HOST'].presence || 'localhost' %>
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>
  username: <%= ENV['DEVELOPMENT_DATABASE_USERNAME'] %>
  password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['TEST_DATABASE_HOST'].presence || 'localhost' %>
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  username: <%= ENV['TEST_DATABASE_USERNAME'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
  statement_limit: <%= ENV['STATEMENT_LIMIT'].presence || 1000 %>
